packages:
  - "backend"
  - "frontend"
  - "e2e"
  - "scripts"
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
minimumReleaseAgeExclude:
  - '@rolldown/binding-darwin-x64@1.2.5'
  - '@rolldown/binding-linux-arm64-gnu@1.2.5'
